/**
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: src/test.js
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 * Summary: Example file to demonstrate Project Packager functionality
 */

// Example function with JSDoc comment
/**
 * Calculates the sum of two numbers
 * @param {number} a - First number
 * @param {number} b - Second number
 * @returns {number} The sum of a and b
 */
function add(a, b) {
  return a + b;
}

// Example class with block comment
/*
 * A simple counter class to demonstrate
 * multi-line block comments
 */
class Counter {
  constructor() {
    this.count = 0;
  }

  increment() {
    this.count++;
  }

  getCount() {
    return this.count;
  }
}

// Example usage
const counter = new Counter();
counter.increment();
console.log(`Counter value: ${counter.getCount()}`);
console.log(`Sum of 5 and 3: ${add(5, 3)}`);
